# This is a basic workflow to help you get started with Actions
name: TestComplete test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run TestComplete
        run: |
          echo "Running TestComplete"
          .\runner.bat
